mysql:
  host: 127.0.0.1
  port: 3306
  db: survey
  config: charset=utf8mb4&parseTime=true
  user: root
  password: LPDz2mb7F8dZqyYz
  log_level: dev
logger:
  level: info
  prefix: '[survey]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: "0.0.0.0"
  port: 8080
  env: debug
jwt:
  secret: ypuUHDIsn78js90#hdHDIua
  exp: 24
redis:
  addr: 127.0.0.1
  port: 6379
  password: LPDz2mb7F8dZqyYz
  db: 0
  pool_size: 100