mysql:
  host: 127.0.0.1
  port: 3306
  db: survey
  user: root
  password: LPDz2mb7F8dZqyYz
  log_level: dev
logger:
  level: info
  prefix: '[gin_project]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: "0.0.0.0"
  port: 8080
  env: dev
